//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersClient.CheckersServer
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Model;

    // Service contract — sync operations only, mirroring the server.
    // The Async wrappers below the interface are client-side helpers,
    // not separate WSDL operations.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(
        ConfigurationName = "CheckersClient.CheckersServer.ICheckersService")]
    public interface ICheckersService
    {
        // ---- Auth ----
        [System.ServiceModel.OperationContractAttribute] LoginResult Login   (string username, string password);
        [System.ServiceModel.OperationContractAttribute] LoginResult Register(string username, string password, string email,
                                                                              System.DateTime? birthDate, string country);
        [System.ServiceModel.OperationContractAttribute] void        Logout  (System.Guid token);

        // ---- Matchmaking ----
        [System.ServiceModel.OperationContractAttribute] string JoinQueue   (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] void   LeaveQueue  (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] string JoinBotGame (System.Guid token);

        // ---- Game state ----
        [System.ServiceModel.OperationContractAttribute] GameStateDto       GetCurrentGame        (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] List<List<Square>> GetLegalMovesForSquare(System.Guid token, int file, int rank);
        [System.ServiceModel.OperationContractAttribute] List<Move>         GetMoveHistory        (int gameId);

        // ---- Game actions ----
        [System.ServiceModel.OperationContractAttribute] MoveResult MakeMove(System.Guid token, List<Square> path);
        [System.ServiceModel.OperationContractAttribute] MoveResult Resign  (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] void       OfferDraw     (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] MoveResult RespondToDraw(System.Guid token, bool accept);

        // ---- Profiles ----
        [System.ServiceModel.OperationContractAttribute] UserProfileDto GetUserProfile         (int userId);
        [System.ServiceModel.OperationContractAttribute] void           UpdateMyEmail          (System.Guid token, string email);
        [System.ServiceModel.OperationContractAttribute] void           ChangeMyPassword       (System.Guid token, string currentPassword, string newPassword);
        [System.ServiceModel.OperationContractAttribute] void           UpdateMyProfilePicture (System.Guid token, byte[] image);

        // ---- Read-only ----
        [System.ServiceModel.OperationContractAttribute] List<User>       GetTopPlayers   (int count);
        [System.ServiceModel.OperationContractAttribute] List<GameRecord> GetMyGameHistory(System.Guid token);
        [System.ServiceModel.OperationContractAttribute] List<User>       GetOnlinePlayers();

        // ---- Admin ----
        [System.ServiceModel.OperationContractAttribute] List<User>       AdminGetAllUsers   (System.Guid token);
        [System.ServiceModel.OperationContractAttribute] bool             AdminBanUser       (System.Guid token, int userId, bool banned);
        [System.ServiceModel.OperationContractAttribute] List<GameRecord> AdminGetRecentGames(System.Guid token, int count);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckersServiceChannel
        : ICheckersService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckersServiceClient
        : System.ServiceModel.ClientBase<ICheckersService>, ICheckersService
    {
        public CheckersServiceClient() { }
        public CheckersServiceClient(string endpointConfigurationName)
            : base(endpointConfigurationName) { }
        public CheckersServiceClient(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress) { }
        public CheckersServiceClient(string endpointConfigurationName,
                                     System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress) { }
        public CheckersServiceClient(System.ServiceModel.Channels.Binding binding,
                                     System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress) { }

        // ---- Synchronous methods (delegate straight to the channel) ----

        public LoginResult Login(string username, string password)
            => base.Channel.Login(username, password);
        public LoginResult Register(string username, string password, string email,
                                    System.DateTime? birthDate, string country)
            => base.Channel.Register(username, password, email, birthDate, country);
        public void Logout(System.Guid token)
            => base.Channel.Logout(token);

        public string JoinQueue   (System.Guid token) => base.Channel.JoinQueue(token);
        public void   LeaveQueue  (System.Guid token) => base.Channel.LeaveQueue(token);
        public string JoinBotGame (System.Guid token) => base.Channel.JoinBotGame(token);

        public GameStateDto GetCurrentGame(System.Guid token)
            => base.Channel.GetCurrentGame(token);
        public List<List<Square>> GetLegalMovesForSquare(System.Guid token, int file, int rank)
            => base.Channel.GetLegalMovesForSquare(token, file, rank);
        public List<Move> GetMoveHistory(int gameId)
            => base.Channel.GetMoveHistory(gameId);

        public MoveResult MakeMove(System.Guid token, List<Square> path)
            => base.Channel.MakeMove(token, path);
        public MoveResult Resign(System.Guid token)
            => base.Channel.Resign(token);
        public void OfferDraw(System.Guid token)
            => base.Channel.OfferDraw(token);
        public MoveResult RespondToDraw(System.Guid token, bool accept)
            => base.Channel.RespondToDraw(token, accept);

        public UserProfileDto GetUserProfile(int userId)
            => base.Channel.GetUserProfile(userId);
        public void UpdateMyEmail(System.Guid token, string email)
            => base.Channel.UpdateMyEmail(token, email);
        public void ChangeMyPassword(System.Guid token, string currentPassword, string newPassword)
            => base.Channel.ChangeMyPassword(token, currentPassword, newPassword);
        public void UpdateMyProfilePicture(System.Guid token, byte[] image)
            => base.Channel.UpdateMyProfilePicture(token, image);

        public List<User>       GetTopPlayers   (int count)         => base.Channel.GetTopPlayers(count);
        public List<GameRecord> GetMyGameHistory(System.Guid token) => base.Channel.GetMyGameHistory(token);
        public List<User>       GetOnlinePlayers()                  => base.Channel.GetOnlinePlayers();

        public List<User>       AdminGetAllUsers   (System.Guid token) => base.Channel.AdminGetAllUsers(token);
        public bool             AdminBanUser       (System.Guid token, int userId, bool banned)
            => base.Channel.AdminBanUser(token, userId, banned);
        public List<GameRecord> AdminGetRecentGames(System.Guid token, int count)
            => base.Channel.AdminGetRecentGames(token, count);

        // ---- Asynchronous wrappers (Task-based) ----
        // These run the sync call on a thread-pool thread so callers
        // can `await` them — same end-effect svcutil produces, but
        // implemented with Task.Run instead of Begin/End plumbing.

        public Task<LoginResult> LoginAsync(string username, string password)
            => Task.Run(() => base.Channel.Login(username, password));
        public Task<LoginResult> RegisterAsync(string username, string password, string email,
                                                System.DateTime? birthDate, string country)
            => Task.Run(() => base.Channel.Register(username, password, email, birthDate, country));
        public Task LogoutAsync(System.Guid token)
            => Task.Run(() => base.Channel.Logout(token));

        public Task<string> JoinQueueAsync   (System.Guid token) => Task.Run(() => base.Channel.JoinQueue(token));
        public Task         LeaveQueueAsync  (System.Guid token) => Task.Run(() => base.Channel.LeaveQueue(token));
        public Task<string> JoinBotGameAsync (System.Guid token) => Task.Run(() => base.Channel.JoinBotGame(token));

        public Task<GameStateDto> GetCurrentGameAsync(System.Guid token)
            => Task.Run(() => base.Channel.GetCurrentGame(token));
        public Task<List<List<Square>>> GetLegalMovesForSquareAsync(System.Guid token, int file, int rank)
            => Task.Run(() => base.Channel.GetLegalMovesForSquare(token, file, rank));
        public Task<List<Move>> GetMoveHistoryAsync(int gameId)
            => Task.Run(() => base.Channel.GetMoveHistory(gameId));

        public Task<MoveResult> MakeMoveAsync(System.Guid token, List<Square> path)
            => Task.Run(() => base.Channel.MakeMove(token, path));
        public Task<MoveResult> ResignAsync(System.Guid token)
            => Task.Run(() => base.Channel.Resign(token));
        public Task OfferDrawAsync(System.Guid token)
            => Task.Run(() => base.Channel.OfferDraw(token));
        public Task<MoveResult> RespondToDrawAsync(System.Guid token, bool accept)
            => Task.Run(() => base.Channel.RespondToDraw(token, accept));

        public Task<UserProfileDto> GetUserProfileAsync(int userId)
            => Task.Run(() => base.Channel.GetUserProfile(userId));
        public Task UpdateMyEmailAsync(System.Guid token, string email)
            => Task.Run(() => base.Channel.UpdateMyEmail(token, email));
        public Task ChangeMyPasswordAsync(System.Guid token, string currentPassword, string newPassword)
            => Task.Run(() => base.Channel.ChangeMyPassword(token, currentPassword, newPassword));
        public Task UpdateMyProfilePictureAsync(System.Guid token, byte[] image)
            => Task.Run(() => base.Channel.UpdateMyProfilePicture(token, image));

        public Task<List<User>>       GetTopPlayersAsync   (int count)         => Task.Run(() => base.Channel.GetTopPlayers(count));
        public Task<List<GameRecord>> GetMyGameHistoryAsync(System.Guid token) => Task.Run(() => base.Channel.GetMyGameHistory(token));
        public Task<List<User>>       GetOnlinePlayersAsync()                  => Task.Run(() => base.Channel.GetOnlinePlayers());

        public Task<List<User>>       AdminGetAllUsersAsync   (System.Guid token) => Task.Run(() => base.Channel.AdminGetAllUsers(token));
        public Task<bool>             AdminBanUserAsync       (System.Guid token, int userId, bool banned)
            => Task.Run(() => base.Channel.AdminBanUser(token, userId, banned));
        public Task<List<GameRecord>> AdminGetRecentGamesAsync(System.Guid token, int count)
            => Task.Run(() => base.Channel.AdminGetRecentGames(token, count));
    }
}
